### ISSUE TITLE
功能改进：使用msgpack存储向量索引

### ISSUE THREAD

**Issue by leolee9086** [leolee9086/SiyuanAssistantCollection#26]
https://github.com/leolee9086/SiyuanAssistantCollection/issues/31

**Comment by zxhd863943427** [comment]
在使用另一种格式前需要先改进fs.readFile，这个模块依赖于思源的getFile，但是它的文件头识别有问题，大概大于15mb的二进制msgpack会被识别为text/plant返回，导致解析出错。目前我是加了一个bin开关，默认为false，然后使用了 `isText && !bin` 来确认是否返回string

**Comment by leolee9086** [comment]
是思源后端接口返回的head值有问题还是fs本身的问题？

**Comment by zxhd863943427** [comment]
思源后端接口返回head的问题。

**Comment by zxhd863943427** [comment]
思源貌似不能正确的识别文件类型，会不确定地返回head，从这个角度来说，最好调用者传入类型来控制返回结果。

**Comment by leolee9086** [comment]
![image](https://github.com/leolee9086/SiyuanAssistantCollection/assets/19915077/a7f9530a-1c49-406a-86ae-d82fa321fb85)
不对啊，思源也是根据扩展名给响应头的来着
