### ISSUE TITLE
一个奇怪的问题，在开启并产生一定量的tip后，会呈现出卡住的情况，旁边的tip不再生成当前块的搜索结果。

### ISSUE THREAD

**Issue by zxhd863943427** [leolee9086/SiyuanAssistantCollection#34]
![图片](https://github.com/leolee9086/SiyuanAssistantCollection/assets/74853597/7d80b5f4-7960-43a2-82ba-0d6f10d29edb)

然而，使用菜单的智能插入引用又能正常使用。
![图片](https://github.com/leolee9086/SiyuanAssistantCollection/assets/74853597/7d7e53a2-c0a1-479a-8374-8495bc8850cf)

**Comment by leolee9086** [comment]
这个应该是tips那边写飞了
