### ISSUE TITLE
Spark对接模块问题，AI聊天显示Undefined

### ISSUE THREAD

**Issue by Lantern51816** [leolee9086/SiyuanAssistantCollection#56]
控制台报错详细内容如下
<img width="659" alt="93b319d1181c645f73b907430f615930" src="https://github.com/leolee9086/SiyuanAssistantCollection/assets/133509688/7ad471ff-201a-4b98-ad9b-9ddc20aa3f29">

**Comment by leolee9086** [comment]
下个版本这里会加强校验，另外spark文档的url那里写着ws(s)的地方的意思是填写ws或者wss，不要写ws(s)哒
