### ISSUE TITLE
docekr部署的siyuan无法打开

### ISSUE THREAD

**Issue by kokojacket** [leolee9086/SiyuanAssistantCollection#72]
下载后没有提示不兼容，弹出下载窗口一直100%，无法打开设置
![image](https://github.com/leolee9086/SiyuanAssistantCollection/assets/74887370/0c94944b-3917-4f88-8124-70af20c442c2)

**Comment by leolee9086** [comment]
刷新之后能够访问吗？

**Comment by leolee9086** [comment]
如果不行的话应该是这几个版本不小心弄丢了网页端支持，下个版本恢复

**Comment by kokojacket** [comment]
不行，刷新和重启容器都不行，坐等大佬更新

**Comment by leolee9086** [comment]
看来我要部署一个思源docker版测试用了，懒还是懒不得

**Comment by leolee9086** [comment]
https://github.com/leolee9086/SiyuanAssistantCollection/issues/73

**Comment by leolee9086** [comment]
https://github.com/leolee9086/SiyuanAssistantCollection/issues/74

**Comment by leolee9086** [comment]
新版应该已经修复了网页端支持，清理缓存并硬刷新之后应该就能够恢复访问，issue我先关闭了，如果有问题我们再说

**Comment by kokojacket** [comment]
是下一个版本吗？

**Comment by leolee9086** [comment]
额 抱歉抱歉  应该是说下一个版本没错。。。。。

**Comment by leolee9086** [comment]
> 是下一个版本吗？

@kokojacket  帮我留意一下，0.0.22版应该已经修复了docker端了
